### PR TITLE
Node 6 shell option

### PR DESCRIPTION
**Pull request by johanneswuerbach**
When using spawn and the shell option provided by Node >=6,
the command has already been escaped for none windows platforms.

Remove all double quotes and re-escape it for windows.

Fixes https://github.com/IndigoUnited/node-cross-spawn/issues/42

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
> #43 is a great start, but it needs to be refined. The desired behavior looks like this:
> 
> If options.shell === false, then fail with a "not supported message".
> If options.shell is truish, then bypass any escaping; if a shebang is detected, the arg pushed needs to be escaped.
> If options.shell is null, then it basically is the current behavior.
> Tests that need to be added:
> 
> The test added in #43
> Test that shebang works with shell:true, asserting that the arg pushed is correctly escaped
> Additionally two README notes should be added:
> 
> Say we do not support shell:false
> Say that if shell:truish, we do not perform any escaping (similar to NodeJS) and should be done carefully.
> Let me know if you want to work on this, otherwise I will pick it up when I get some time.

@satazor I added some comments to the README and additional tests around trying `{ shell: false}` when a shell is required. WDYT?

> Test that shebang works with shell:true, asserting that the arg pushed is correctly escaped

I didn't fully understood what you mean by this, could you elaborate?

**Comment by satazor** [comment]
@johanneswuerbach nvm, ignore that because if there's a shebang with special chars, it's already escaped.

**Comment by johanneswuerbach** [comment]
@satazor looks like this passed now. Not super happy about the test, but didn't had a better idea and my Windows VM stop running a while ago :-(

**Comment by satazor** [comment]
@johanneswuerbach I think we should use nodejs spawn also when `shell:false`.

**Comment by satazor** [comment]
#45 Is pretty much ready. One question though: do you think that `cross-spawn` should fail when `options.shell` was specified when running on node < 6?

**Pull request closed without merging**
