### PR TITLE
Optional spawn sync

### PR DESCRIPTION
**Pull request by johanneswuerbach**
Compiling native extensions requires a working compiler toolchain

Related: https://github.com/airportyh/testem/issues/588

### CODE REVIEW

**Comment by satazor** [comment]
//cc @BigstickCarpet

**Comment by BigstickCarpet** [comment]
@johanneswuerbach - I think this is actually an issue with [Spawn Sync](https://github.com/ForbesLindesay/spawn-sync), not `Cross Spawn`.  Perhaps send them a pull request instead?

If we make `spawn-sync` an optional dependency, then we have **no** graceful fallback for Node < 0.12.  Our only option is to throw a runtime error, which is not ideal.  On the other hand, if Spawn Sync makes `thread-sleep` an optional dependency, then it has a graceful fallback (it falls-back to a simple loop)

**Comment by BigstickCarpet** [comment]
It looks like Spawn Sync is doing some strange stuff in their [package.json file](https://github.com/ForbesLindesay/spawn-sync/blob/master/package.json).  They don't depend on `thread-sleep` directly, they depend on `try-thread-sleep`, which in-turn depends on `thread-sleep`.  What's odd is that `try-thread-sleep` isn't listed as a dependency or optionalDependency, but rather as a devDependency.  They then use a [post-install script](https://github.com/ForbesLindesay/spawn-sync/blob/master/postinstall.js) to install it as a dependency.  I'm not sure why they're doing it that way.

The other weird thing is that `try-thread-sleep` has `thread-sleep` as an **optional** dependency, which means this whole issue should be moot, since nowhere in the entire dependency chain is `thread-sleep` actually a dependency of _anything_.  So, as far as I can tell, `thread-sleep` (which is the native C module that's causing the whole issue) shouldn't ever actually get installed unless an app explicitly declares it as a dependency.

Or am I missing something?

**Comment by johanneswuerbach** [comment]
Maybe @ForbesLindesay knows more?

Also //cc @stefanpenner

**Comment by stefanpenner** [comment]
you are correct, it is in spawn-sync.

@johanneswuerbach the issue in testem is, one cannot use sync spawn of anykind in node < 0.12 without a native extension. So it should be confirmed testem itself doesn't rely on that

**Comment by johanneswuerbach** [comment]
Yep, testem is only using the async version. I'll lock to `0.2.9` until this is resolved.

**Comment by stefanpenner** [comment]
> Yep, testem is only using the async version. I'll lock to 0.2.9 until this is resolved.

:+1:

**Comment by johanneswuerbach** [comment]
Issue created. Closing.

**Comment by ForbesLindesay** [comment]
Spawn-sync only has an optional native dependency (if that fails to build it falls back to busy waiting which is bad for performance but works fine). You will get an error message during installation, which you can safely ignore.

**Comment by stefanpenner** [comment]
> but works fine)

unfortunately, there is no way to reasonable silence the failure. Users become confused and assume the install failed entirely :(

**Pull request closed without merging**
