### PR TITLE
Node 4.8 supports the shell option for spawn

### PR DESCRIPTION
**Pull request by johanneswuerbach**
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V4.md#4.8.0

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
The Node 0.10 failure seems unrelated.

**Comment by johanneswuerbach** [comment]
https://github.com/ForbesLindesay/try-thread-sleep/pull/1 should fix the Node 0.10 issue

**Comment by satazor** [comment]
Cool! @ForbesLindesay can you merge and land https://github.com/ForbesLindesay/try-thread-sleep/pull/1?

**Comment by ForbesLindesay** [comment]
Done

**Pull request merged**
