### PR TITLE
Use `spawn-sync` for backwards compatibility with 0.10

### PR DESCRIPTION
**Pull request by kevva**
This adds backwards compatibility with node 0.10.

### CODE REVIEW

**Comment by BigstickCarpet** [comment]
:+1:   Good idea.

**Comment by satazor** [comment]
Tests passing on windows, linux and mac?

**Comment by kevva** [comment]
At least on Linux and Windows.

**Comment by satazor** [comment]
Will test on mac

**Comment by satazor** [comment]
@BigstickCarpet can you please test the master branch on windows? working well on mac and linux

**Comment by satazor** [comment]
I don't have my usual windows vm in this computer.

**Comment by satazor** [comment]
I ended up testing on windows, everything worked fine on node 0.10. Thanks!

**Comment by BigstickCarpet** [comment]
Awesome!  Great to hear.  This'll be **so** useful for **so** many of my build scripts and Yeoman generators.

**Pull request merged**
