### PR TITLE
Only spawn cmd.exe if necessary

### PR DESCRIPTION
**Pull request by timdp**
See #32.

I wasn't sure how to test whether cmd.exe got spawned. I ended up checking the parent process ID of the spawned process using WMI, as Node doesn't support it out of the box.

### CODE REVIEW

**Comment by satazor** [comment]
Build in appveyor is not passing.

> I wasn't sure how to test whether cmd.exe got spawned. I ended up checking the parent process ID of the spawned process using WMI, as Node doesn't support it out of the box.

You could just test it with parse().

**Comment by timdp** [comment]
> Build in appveyor is not passing.

The reason why it fails (only) with Node 0.10 is because `['foo', '', 'bar']` gets collapsed. Is that a known issue with 0.10 then? If so, should we always spawn cmd on 0.10 or quote the args ourselves?

> You could just test it with parse().

You mean not run the actual command and see what it returns? I thought you were going more for integration testing, but I can definitely add a unit test for that as well.

**Comment by satazor** [comment]
> The reason why it fails (only) with Node 0.10 is because ['foo', '', 'bar'] gets collapsed. Is that a known issue with 0.10 then? If so, should we always spawn cmd on 0.10 or quote the args ourselves?

Hmm but in Node 0.10 on linux this is passing.. this is strange.

**Comment by timdp** [comment]
My guess would be that Node 0.10 doesn't quote the empty string before passing it to cmd.exe, although then it would sound like quoting e.g. strings with spaces would also be broken. I'll write a minimal test.

**Comment by timdp** [comment]
Well, this is fun. With `child_process.spawn('node', ['child.js', 'abc', '', 'def'], {stdio: 'inherit'})` and `child.js` simply logging `process.argv`:

```
Tim@CP C:\src\spawn-test-2
> nvm use 4.4.4
Now using node v4.4.4 (64-bit)

Tim@CP C:\src\spawn-test-2
> node index.js
[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\src\\spawn-test-2\\child.js',
  'abc',
  '',
  'def' ]
code 0

Tim@CP C:\src\spawn-test-2
> nvm use 0.10.45
Now using node v0.10.45 (64-bit)

Tim@CP C:\src\spawn-test-2
> node index.js
[ 'node', 'C:\\src\\spawn-test-2\\child.js', 'abc', 'def' ]
code 0
```

Strings with spaces and quotes work fine though. It's just empty strings that cause breakage.

**Comment by satazor** [comment]
So basically I was fixing a nodejs windows bug in v0.10 lol. Can we also exec cmd.exe if there are empty args?

**Comment by timdp** [comment]
Yeah, interesting find. At least it got fixed in 0.12.

Even though other strings worked fine, this does not inspire confidence in 0.10. Doesn't it seem safer to run everything through cmd in 0.10? I'm happy to implement either solution; just wanted to suggest it again.

**Comment by satazor** [comment]
Yes, we can also run everything through cmd.exe in v0.10. I don't have a strong opinion on both solutions so I trust on your choice.

**Comment by timdp** [comment]
Muito bom. Currently waiting for tests.

**Comment by satazor** [comment]
> Muito bom. Currently waiting for tests.

Learning portuguese? Tests on appveyor are so damn slow :(

**Comment by timdp** [comment]
Through Google Translate, yeah. :-)

In all fairness, I force-pushed twice to fix a spawn-sync issue. But yeah, a lot slower than Travis.

**Comment by satazor** [comment]
Regarding semver, do you think it might make sense to bump major? I'm afraid that this could unexpectedly break some use-cases.

**Comment by timdp** [comment]
Not sure either. On the one hand, it's minor in that the module never actually promised to run the command through a shell, just that it would support all the additional features which happened to require a shell in many cases. On the other hand, it's major because the internals have changed a little and may indeed cause compatibility issues--although it shouldn't. If this were one of the bigger repos, they'd probably release a beta, but realistically speaking, I'd go for major.

**Comment by satazor** [comment]
I'll go for major!

**Pull request merged**
